### ISSUE TITLE
User + key management

### ISSUE THREAD

**Issue by eliocamp** [khufkens/ecmwfr#17]
In thinking about the user verification it occur to me that currently there's no way of knowing is an user/password belongs to the webapi or the cds service. Should there be a `service` argument to `wf_set_key()` and the rest? 

PS: You are free to tell me if I'm opening too many issues :sweat_smile:

**Comment by khufkens** [comment]
Actually, this was implemented at some point. 

Then I decided to remove it, for simplicity, as both the webapi and CDS use unique UID schemes (ECWMF uses email, CDS a random number). A week ago I tried to implement the CAMS atmospheric data and their api (http://macc-raq-op.meteo.fr/doc/Guide_Numerical_Data_CAMS_new.pdf). 

Obviously, this one uses the email address again. 🤦‍♂️ So, yes... it would make sense to future proof things.

**Comment by khufkens** [comment]
Also, don't mind the issues, as long as you help out solving them :smile:

**Comment by eliocamp** [comment]
Perfect! 
Then in the `service` argument of the keyring I'll use something like `ecmwfr_webapi`/`ecmwfr_cds`.

**Comment by khufkens** [comment]
I think this should be documented well, then this shouldn't be too much of an issue.

**Comment by khufkens** [comment]
Actually, if you are still working on the readLines approach this could be a question that pops up. So people don't have to punch in the argument either. But I guess you had that covered.
