### ISSUE TITLE
Problem with locked keyring

### ISSUE THREAD

**Issue by eliocamp** [khufkens/ecmwfr#25]
I updated my OS and had to setup the keys again in my computer and was getting this error:
```
Secret service keyring error in 'set': 'Cannot create an item in a locked collection'
```
I had to use `keyring::keyring_unlock()` and then it worked. I'm not familiar with managing keyrings but, would it be necessary to add this command before adding (or retrieving?) keys?

**Comment by khufkens** [comment]
Keyrings have the option to have a separate password from the main login. Depending on the system you might also not unlock it by default on login into your account. In most cases this does work.

So yes, for robustness we should add this. The `keyring_is_locked()` function returns TRUE/FALSE on the state of the lock. In this case if TRUE, we should call `keyring_unlock()` which will present a prompt for the password.

Fixed this here https://github.com/khufkens/ecmwfr/commit/8884c080045fa645915faa54a51709344d6a8ce0

Simple if statements, don't think it warrants a separate function.
