### ISSUE TITLE
Notify when download starts 

### ISSUE THREAD

**Issue by eliocamp** [khufkens/ecmwfr#39]
Right now the package makes a request to the data url and downloads the content and if it's not a binary file, then it continues to poll the server in the same manner. The problem is that as a user, there's no real indication of when the file is ready and the script started to download. Furthermore, there's no way of indicating progress. 

I seem to have missplaced the URL with the API documentation, but I remember that the url with the request ID was supposed to return a different status code for each case. In this case, then we could change [this line](https://github.com/khufkens/ecmwfr/blob/75e831f56fa3e6f41d8eb06a7519e965abe7a292/R/wf_transfer.R#L90) and instead of getting the full content, getting only  `httr::status_code(response)` and testing on it. One it get's the a-ok for download, then inform the user and get the content. 

This setup would also allow to download files bigger than RAM, since we can potentially bypass loading the content into memory. 

If you think it's a good idea, I could do it myself. However, as I said, I'm not finding the correct documentation page and I don't remember which status code was which. (embarrasing! 😳️)

**Comment by khufkens** [comment]
I think this is what I do here:
https://github.com/khufkens/ecmwfr/blob/75e831f56fa3e6f41d8eb06a7519e965abe7a292/R/wf_transfer.R#L120

Tracking status code 202.

The problem is that the transfer would start regardless. Basically the API does provide status code but I'm not sure how to "just" get the header of a file, without grabbing the whole file. This is what's needed for this to work.

**Comment by eliocamp** [comment]
Yeah, I've now realised that the GET verb downloads the whole content and the content() function just extracts it. 
It seems that the correct way of downloading just the status code is with a HEAD request, but I tried it and it seems that the server does not support it.

**Comment by khufkens** [comment]
This was my recollection of it as well. The python code behaves in much the same way. The basic framework is almost a direct port of the python package (in handling the requests). They didn't make the provision either. What you can do is do the call, cancel the session, save the url, check online and THEN download. This works for scheduling large queries. But, with the jobs in RStudio some of this has been resolved as well (not hogging a terminal).

**Comment by eliocamp** [comment]
I've found that using the command line tool curl, I can get the status using 

```bash
curl -s -I -X GET URL -H "Accept: application/json" -H "Content-Type: application/json" -H "From: USER" -H "X-ECMWF-KEY: KEY" 
```

The magical parameter there is the `-I` flag. I'd need to poke into the httr package (or the curl package) to see how to run it from R with that flag on.

**Comment by khufkens** [comment]
Let me know what you figure out.

**Comment by khufkens** [comment]
btw. if there is no httr support we might want to put in a ticket for it!

**Comment by eliocamp** [comment]
I've been searching with no luck. I'll open an issue in httr or curl to see if there's a direct option. However I did came up with this possible alternative (from an issue in httr):

```r
retrieve_header <- function(url, headers) {
  handle <- curl::new_handle()
  curl::handle_setheaders(handle, .list = headers)
  con <- curl::curl(url, handle = handle)

  open(con, "rf")
  head <- curl::handle_data(handle)
  close(con)
  
  head$headers <- curl::parse_headers_list(head$headers)
  return(head)
}

h <- retrieve_header(url, list("Accept" = "application/json",
                          "Content-Type" = "application/json",
                          "From" = user,
                          "X-ECMWF-KEY" = key))

h$status_code
```

This seems to work ok on the webapi interface (which I now realise it the only one affected by this issue). It returns code 202 when still processing and 200 when it's done. 

Adding this code would technically add the curl as a dependency, but since it's already an httr dependency, it shouldn't be a problem.
