### ISSUE TITLE
Send failure: Connection was reset

### ISSUE THREAD

**Issue by dominicroye** [khufkens/ecmwfr#42]
I'm trying to get a request but each time I only get this message (after a short time). 

```
- timeout set to 1.0 hours
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Send failure: Connection was reset
```
The thing is that on cds.climate.copernicus the request is still in progress. Any idea what to do?

**Comment by khufkens** [comment]
This is normal behaviour, the process will wait for 1 hour and then quit (as indicated by the error). This prevents the process from hogging a session or terminal.  You can change the time out value in `wf_request()` to your own setting if your data is larger, or CDS is slow for this data or day.

See the documentation on on `wf_request()` here: https://khufkens.github.io/ecmwfr/reference/wf_request.html
