### ISSUE TITLE
Date period specification

### ISSUE THREAD

**Issue by danielreispereira** [khufkens/ecmwfr#43]
Documentation says:

> For those familiar to ECMWFs mars syntax: CDS does not accept date = "2000-01-01/to/2000-12-> 31" specifications at the moment. It is possible to specify one specific date via date = "2000-01-> >01" or multiple days via date = ["2000-01-01","2000-01-02","2000-10-20"] but not via ".../to/...".

So, how should the "date" piece of request be built when I need to extract date1 to date2?
> date           = "[2018-01-30  , 2019-02-01]",     #does not work
> date           = "['2018-01-30', '2019-02-01']",  #does not work
> date           = '["2018-01-30", "2019-02-01"]', #does not work

**Comment by khufkens** [comment]
Try:
```date = ["2000-01-01","2000-01-02","2000-10-20"]```
no quotes

**Comment by danielreispereira** [comment]
See image below. 
RStudio will complain that I'm not building a list with "QuotedStrings" if I try that. 

Looks like I'll have to build the character string with paste(), not sure. Thoughts?

![image](https://user-images.githubusercontent.com/4158858/65976242-3801da80-e446-11e9-8cd2-148e622e2972.png)


![image](https://user-images.githubusercontent.com/4158858/65976363-65e71f00-e446-11e9-83a1-da0aad86dcc2.png)

**Comment by khufkens** [comment]
Try converting the request from python to R using the addin.

A query similar to this should work.
```
request <- list(
  product_type = "reanalysis",
  format = "netcdf",
  variable = "temperature",
  pressure_level = "850",
  year = "1980",
  month = "02",
  day = c("02", "03"),
  time = "01:00",
  area = "70/-20/30/60",
  dataset = "reanalysis-era5-pressure-levels",
  target = "download.nc"
)
```
