### ISSUE TITLE
wf_request problem

### ISSUE THREAD

**Issue by vegvarizs** [khufkens/ecmwfr#49]
Hi,
after successfully completing the wf_set_key command using my uid as user identity, the wf_request command terminates with an error message (using a sample request list) :
Error in FUN(X[[i]], ...) : argument is missing, with no default
Calls: sourceWithProgress ... eval -> eval -> wf_request -> which -> vapply -> FUN
In addition: Warning messages:
1: In default_backend_auto() :
  Selecting ‘env’ backend. Secrets are stored in environment variables
2: In default_backend_auto() :
  Selecting ‘env’ backend. Secrets are stored in environment variables
3: In default_backend_auto() :
  Selecting ‘env’ backend. Secrets are stored in environment variables
4: In default_backend_auto() :
  Selecting ‘env’ backend. Secrets are stored in environment variables
Execution halted

What can be the problem?

Bests,
Zsolt

**Comment by eliocamp** [comment]
@vegvarizs, There's a small but in the current version when your system doesn't support keyrings. See here: https://github.com/khufkens/ecmwfr/issues/46
You can try installing [this](https://github.com/khufkens/ecmwfr/pull/47] pull request version with 

```r
remotes::install_github("khufkens/ecmwfr", ref = remotes::github_pull(47))
```

**Comment by vegvarizs** [comment]
Thanks, I have installed it, but the same problem prevails. The libsodium is also installed on my Ubuntu. Still experiencing.

**Comment by khufkens** [comment]
Have you used `keyring` package in another context so the environmental variables are mixed up?

**Comment by vegvarizs** [comment]
Yes! Should I remove it and reinstall ecmwfr?

**Comment by khufkens** [comment]
Just try, but be sure to reinstall `keyring` as well.

**Comment by vegvarizs** [comment]
Done: the warning messages about the backend environment disappeared, but the message:

Error in FUN(X[[i]], ...) : argument is missing, with no default
Calls: sourceWithProgress ... eval -> eval -> wf_request -> which -> vapply -> FUN
Execution halted

is still there.
I am using this request:
wf_request(request = request, user = uid, transfer = TRUE, job_name = "vzs.test", path = ".")

**Comment by khufkens** [comment]
Drop the . from the job name and use an explicit path name. Then try again. I don't think this is an authentication error.

**Comment by vegvarizs** [comment]
The same problem persists (also with and without invoking library(keyrings).

2019. 12. 20. 22:14 keltezéssel, Koen Hufkens írta:

**Comment by khufkens** [comment]
Could you run the example code as listed in the documents for me and provide all the code as you run it. (see https://khufkens.github.io/ecmwfr/articles/cds_vignette.html)

Also provide the system you use both in terms of software and hardware. With just a vague error message and no knowledge of what you run I can't do much but guess toward the problem.

```
# Specify the data set
request <- list("dataset"        = "reanalysis-era5-pressure-levels",
                "product_type"   = "reanalysis",
                "variable"       = "temperature",
                "pressure_level" = "850",
                "year"           = "2000",
                "month"          = "04",
                "day"            = "04",
                "time"           = "00:00",
                "area"           = "70/-20/30/60",
                "format"         = "netcdf",
                "target"         = "era5-demo.nc")

# Start downloading the data, the path of the file
# will be returned as a variable (ncfile)
ncfile <- wf_request(user = "2088", # <-- your USER ID HERE
                      request = request,   
                      transfer = TRUE,  
                      path = "~",
                      verbose = FALSE)

```

**Comment by vegvarizs** [comment]
Thanks! I wish you a Happy New Year!

I tried, but it still results in "Error in FUN(X[[i]], ...) : argument 
is missing, with no default'

On Ubuntu 18.04, using RStudio with R3.4.4., I run the following code:

library(ecmwfr)
wf_set_key(user = "31712", key=mykey, service = "cds") #successfully 
completed
request <- list("dataset"        = "reanalysis-era5-pressure-levels",
                 "product_type"   = "reanalysis",
                 "variable"       = "temperature",
                 "pressure_level" = "850",
                 "year"           = "2000",
                 "month"          = "04",
                 "day"            = "04",
                 "time"           = "00:00",
                 "area"           = "70/-20/30/60",
                 "format"         = "netcdf",
                 "target"         = "era5-demo.nc")
# Start downloading the data, the path of the file
# will be returned as a variable (ncfile)
ncfile <- wf_request(user = "31712", # <-- your USER ID HERE
                       request = request,
                       transfer = TRUE,
                       path = "~",
                       verbose = FALSE)

Best,
Zsolt




2019. 12. 26. 13:22 keltezéssel, Koen Hufkens írta:

**Comment by khufkens** [comment]
You run a rather old version of R, lots changed between 3.4 and 3.6.

I would upgrade and try again. This seems like a likely cause as my unit tests (using the code above) come out clean on 3.6. Previously they ran on 3.4 but since a little while it is 3.6 by default.

**Comment by vegvarizs** [comment]
Thanks, I will try.

2020. 01. 02. 13:25 keltezéssel, Koen Hufkens írta:

**Comment by eliocamp** [comment]
I installed R 3.4.4 and using the CRAN version of the package I didn't get any error. But I can reproduce using the development version. I'll look into it.

**Comment by eliocamp** [comment]
There! It was a trailing comma in one function call. It seems that R 3.4.4 treats it as expecting another argument while R 3.6 doesn't.

**Comment by vegvarizs** [comment]
Thanks! I will manage that.

2020. 01. 02. 21:42 keltezéssel, Elio Campitelli írta:
