### ISSUE TITLE
Default request as function default value

### ISSUE THREAD

**Issue by retostauffer** [khufkens/ecmwfr#5]
In `wf_request` a default is set for the `request` input parameter. I would set this as one of the required parameters ([line 38+](https://github.com/retostauffer/ecmwfr/blob/893e9993a631e34be338ad576ce8e227586a2421/R/wf_request.R#L38)):

In addition, don't you think that the default `transfer` should be set to `TRUE`? I guess that the 'standard-user' might have easy access to the data and will not use `ecmwfr` as a 'queue-batch-submit script'?

```
wf_request <- function(
  email,
  path = tempdir(),
  time_out = ifelse(request$dataset == "mars", 3*3600, 3600),
  transfer = FALSE,
  request = list(stream = "oper",
                 levtype = "sfc",
                 param = "167.128",
                 dataset = "interim",
                 step = "0",
                 grid = "0.75/0.75",
                 time = "00",
                 date = "2014-07-01/to/2014-07-02",
                 type = "an",
                 class = "ei",
                 area = "50/10/51/11",
                 format = "netcdf",
                 target = "tmp.nc"),
  verbose = TRUE

```

**Comment by khufkens** [comment]
removed default query and shuffled the order in `wf_request()`
