### ISSUE TITLE
CRAN issue, ... in @param not in function

### ISSUE THREAD

**Issue by khufkens** [khufkens/ecmwfr#58]
Not sure why this is detected right now and not like x months ago as nothing changed.

Anyway, `@param` here should be removed.

https://github.com/khufkens/ecmwfr/blob/60d2b35fc1fd1eaf92505dea5e7b9db36ae79ed3/R/wf_transfer.R#L13

```
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_ecmwfr.html>.

Specifically, see the warnings about 'Documented arguments not in
\usage' in the r-devel checks.  These are from a recent bug fix
(PR#16223, see
<https://bugs.r-project.org/bugzilla/show_bug.cgi?id=16223>): can you
please fix your man pages as necessary?  (In most cases, remove the
documentation for argument '...'.)

Please correct before 2020-02-17 to safely retain your package on CRAN.

Best,
-k

```

**Comment by khufkens** [comment]
@eliocamp, will fix next week.

**Comment by eliocamp** [comment]
It's bizarre that the issue wasn't flagged in CRAN checks before 🧐️!

**Comment by khufkens** [comment]
Yep, and still it only gives warnings in some occasions. Weird stuff.

**Comment by khufkens** [comment]
Fixed as per:
https://github.com/khufkens/ecmwfr/commit/7a9d92013ec3b3b0f49e6eef821db63fcf677eaa
