### ISSUE TITLE
Selection spatial window

### ISSUE THREAD

**Issue by rasillad** [khufkens/ecmwfr#59]
Dear friend, I am trying to download a spatial subset of the Thermal comfort indices database, using ecmwfr. 
I am facing two problems: I am not able to donwload the required spatial window requested by the order 'area' (the size of the file seems to be the whole global spatial coverage 90N-60S, 180W-180E)
and also I am not able to open neither the resulting tar.gz file nor the zip alternative file in my PC, using winrar.
am I doing something wrong with the syntax?
Best regards
request <- list(
  'dataset' = "derived-utci-historical",
  'variable' = "Universal thermal climate index",
  'product_type' = "Consolidated dataset",
  'year' = "1979",
  'month' = "01",
  'day' = "01",
  'area' = "50/-10/35/5",
  'format' = "tgz",
  'target' = "download.tar.gz")

**Comment by khufkens** [comment]
The products seems new in the CDS catalogue so I think they might not yet offer spatial subsets. You will have to check with the ECMWF for this.

I selected two days, and this made it possible to open the file, for some reason a single day doesn't work. Not sure on which end the issue sits (I would argue CDS as the client is just a download wrapper).

This works for me:

```r
request <- list(
  format = "zip",
  variable = "Universal thermal climate index",
  product_type = "Consolidated dataset",
  year = "1979",
  month = "01",
  day = c("01","02"),
  dataset = "derived-utci-historical",
  target = "download.zip"
)

wf_request(user = "2088",
           request = request,   
           transfer = TRUE,  
           path = "~/Desktop/",
           verbose = TRUE)
```
Reading in one file and plotting the data gives:

![Rplot](https://user-images.githubusercontent.com/1354258/77348952-972c1200-6d3a-11ea-812f-f95cb73c5d76.png)
