### ISSUE TITLE
Error in wf_check[[correct]] : attempt to select less than one element in get1index

### ISSUE THREAD

**Issue by DHwreckage** [khufkens/ecmwfr#62]
Hi,

i am trying to download a massive amount of data from ERA5 and have been running into the error in the title. i have now gone back into to the demo on CRAN and am still getting the error, the script is straight from the demo:

# Specify the data set
request <- list("dataset"        = "reanalysis-era5-pressure-levels",
                "product_type"   = "reanalysis",
                "variable"       = "temperature",
                "pressure_level" = "850",
                "year"           = "2000",
                "month"          = "04",
                "day"            = "04",
                "time"           = "00:00",
                "area"           = "70/-20/30/60",
                "format"         = "netcdf",
                "target"         = "era5-demo.nc")

# Start downloading the data, the path of the file
# will be returned as a variable (ncfile)
ncfile <- wf_request(user = "2088",
                     request = request,   
                     transfer = TRUE,  
                     path = "~",
                     verbose = FALSE)

![image](https://user-images.githubusercontent.com/45567604/82705765-8530f780-9c35-11ea-8479-a1903d484a24.png)

any idea what could be causing this?

i am working in R version: 3.6.3-64bit and am using ecmwf version: 1.2.3, when i run the wf_get_key(user = "",service = "cds") it lists my correct key just as a reference.

**Comment by DHwreckage** [comment]
modified request to this and it now functions properly:
request <- list("dataset_short_name" = ""

**Comment by khufkens** [comment]
Forgot to update some of the docs but the website is up-to-date now. Best to look there for info, examples etc.
