### ISSUE TITLE
Problem retrieving multiple variables from CDS 

### ISSUE THREAD

**Issue by seyiaros** [khufkens/ecmwfr#9]
I get error messages when I tried to retrieve multiple variables from the CDS store.  Below is my request list using the ecmwf package:
request <- list("dataset" = "reanalysis-era5-single-levels",
                "product_type" = "reanalysis",
                "variable" = c("10m_u_component_of_wind", "10m_u_component_of_wind",  
               "10m_v_component_of_wind","2m_temperature",  "mean_boundary_layer_dissipation", 
                 "total_precipitation"),
                "year" = "2010",
                "month" = "01",
                "day" = "01",
                "area" = "-28/25/48/22",
                "format" = "netcdf",
                "time" = "00:00",
                "target" = "era5-jan2010.nc")

However,  I am able to retrieve one variable.

Thanks
Seyi

**Comment by khufkens** [comment]
10m_u_component_of_wind is mentioned twice

**Comment by seyiaros** [comment]
Many thanks, @khufkens. Sorry I didn't figure out myself. I have successfully retrieved the variables in the request list.

**Comment by khufkens** [comment]
No worries, always check parameters (and formatting), normally the package just forwards things to the API so whatever is possible in a MARS request should work in the package.
